### PR TITLE
Add `--type` argument to `doing list`

### PR DESCRIPTION
**Pull request by operte**
Related to #60 

I'm wondering what to do about the default type for doing list. I thought about using `default_workitem_type` but that might be a bit weird. 
The alternatives would be to have no default, or to create another config variable. 

In any case, the docs in `config_file.md#optional-parameters` need to be updated.

### CODE REVIEW

**Comment by timvink** [comment]
Nice @operte !

I'd like not to have any default for `type`. So basically default would be `type=None` if not specified, which in turns means no filter on user story type.

Make sure to pull in latest changes from `v1.2` which I am releasing now..

**Comment by timvink** [comment]
We can release this in `v1.2.1` when you're ready!

**Comment by operte** [comment]
I agree, no default is better, so the user needs to be specific. 

I noticed that if I set the default to None, `click` requires it to have an argument:
```zsh
doing list --type   
Error: --type option requires an argument
```

I think this is because for this option we use `click.Choice` and that requires an exact match with one of the choice options. 
I am ok with this. If the user wants to see all work items, they can instead not pass the `--type` option. 
On the other hand, if we want to be explicit, we can also add an `All` option, whose query would be `[System.WorkItemType] <> ''`.

**Comment by timvink** [comment]
I think the behaviour is fine, that `doing list` does not filter on type, but if you use `--type` it validates the input. No need to add 'all' option.

I have one more comment though:

1) There are more work item types ([link](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/about-work-items?view=azure-devops&tabs=cmmi-process)). Missing 'Product Backlog Item', 'Requirement', 'Code Review Request', 'Code Review Response', 'Feedback Request', 'Feedback Response', 'Shared Step', 'Shared Parameter', 'Test Case', 'Test Plan', 'Test Suite', 'Change Request', 'Review', 'Risk'. 

Apparently, you can even add custom work item types (WITs), which we currently don't support. Perhaps best to print a warning when you use a type that is not in the list? And so just have the input to `--type` be a free string.

**Comment by operte** [comment]
That sounds like a good idea :) 

- I changed the default to "" and the type to str
- added some examples of common types in the help
- Changed the type to str also in `issue/commands.py` but left the default and help the same
- Created a function to validate the work item type.

Let me know your thoughts. Perhaps there's a better way of validating the work item type that you can think of.
Also not sure that was the proper way of sending out a warning to the user.

**Comment by timvink** [comment]
Nice work @operte !

**Pull request merged**
