### PR TITLE
optionally assign story points to a new issue

### PR DESCRIPTION
**Pull request by FitzgeraldKrudde**
Add the capability to optionally assign story points to a new issue (work item) i.e. when configured in the config file.

The item in the config file is named: `default_story_points`

### CODE REVIEW

**Comment by timvink** [comment]
Nice idea!

I have some doubts about this one however:

- This will only work when an agile/scrum workflow is enabled in azure devops --> a work item might not have a StoryPoints field in another setting?
- If we continue on this route, there are lots of different commands that can still be added, like 'priority', 'risk', 'value area' and 'acceptance criteria' (see screenshot). These are all less-used fields, but will clutter the `doing issue create --help` adding cognitive overhead
- I have not seen anyone use storypoints with azure devops issues yet, so I am not sure if this a going to be a common workflow.
- Setting a default storypoint might make sense, but done properly, the issues will likely have different storypoints, which you could change via the UI easily
- When you set `--parent`, you are inherenting from another user story. Not clear what the behaviour should be when not specify a user story, or when the default user story points are more than the parent work item story points. 
- I would like to be similar to github's CLI where possible, and [`gh issue create`(https://cli.github.com/manual/gh_issue_create) has limited options.

image

Instead, we could simply add a `-f/--fields` option to `doing create issue`, to allow more advanced users to set any field options. You would then be able to [set a default in the config file](https://ing-bank.github.io/doing-cli/config/config_file/#setting-defaults) like so:

```yaml
defaults:
    DOING_CREATE_ISSUE_FIELDS='Microsoft.VSTS.Scheduling.StoryPoints=10'
```

Granted, this is less elegant than adding a dedicated `-s/--storypoints`, but it keeps things simple & allows for advanced workflows...

Thoughts?

**Comment by FitzgeraldKrudde** [comment]
As the translation to the required arguments in `--fields` is not really trivial (storypoints->Microsoft.VSTS.Scheduling.StoryPoints for example) I would prefer the most common options to have a commandline option/config item and the others could then be added (if needed) by `--fields`. 

The question then is: what is most common.. Definitely open for discussion but I think story points is a common one.

The reason I started with this MR is that our organisation has announced story points to become mandatory (don't know what it will imply exactly) and I looked into story points for the Azure cli when I created a migration script for GL issues to Azure work items. So it seemed a small contrib for me here :-)

**Comment by timvink** [comment]
Ok, let's add storypoints then, and leave the rest for when there is an ask from users.

It needs to be an option to the cli command, and their should not be a config option, rather you can set a default with `defaults`. Shall I merge and pick that up or would you prefer to give it a try ?

**Comment by FitzgeraldKrudde** [comment]
Good! I would like to give it a try :-)

Probably I will pick it up the end of this week.

I hope that's OK (I do not think there is a hurry for this one).

If you feel the urge/need to implement it earlier then that is of course also fine for me.

**Comment by timvink** [comment]
No rush, and let me know if you need some pointers

**Comment by FitzgeraldKrudde** [comment]
Changed the pickup of the value for the story points from config to a cmdline param.

Please have a look and verify

**Comment by timvink** [comment]
Thanks for the contribution! 

I'm going to merge and make the following changes before release:

- set default story points to None instead of 1
- update docs, incl. example of how to set default storypoints
- fix if/else clause (combination with `label`)

**Comment by FitzgeraldKrudde** [comment]
👍

**Pull request merged**
